### PR TITLE
Let user select how often to print progress while running louvain.

### PR DESCRIPTION
**Pull request by Jessime**
Avoiding an `AttributeError`. 

The other two line changes are automatic formatting things done by atom.

### CODE REVIEW

**Review by wweir827 — COMMENTED** [review]
i'm having a little trouble telling which all lines where the changes vs which are formatting things?  what did the atom do here?  Just change comments and split lines?

**Comment by Jessime** [comment]
Github is handling this a bit weird, since I had a PR from the spring. But I've merged in all your changes from then. The "Files changed" tab should let you see the relevant changes:

https://github.com/wweir827/CHAMP/pull/4/files

**Review by wweir827 — APPROVED** [review]

**Comment by wweir827** [comment]
i had also been considering incorporating tqdm for that as well, which has a much nicer progress bar that can be used in tandem with the parallelization.

**Comment by Jessime** [comment]
Solid option. I use `tqmd` for all of my stuff.

**Pull request merged**
